### PR TITLE
Prettier v2

### PR DESCRIPTION
**Pull request by mroderick**
This PR matches up with https://github.com/sinonjs/sinon/pull/2324

### CODE REVIEW

**Comment by mroderick** [comment]
I forgot to update the CI files, I'll add some more commits

**Review by mantoni — APPROVED** [review]

**Review by mantoni — CHANGES_REQUESTED** [review]
Uh, circle not happy.

**Comment by mroderick** [comment]
@mantoni I fixed it :)

**Review by mantoni — APPROVED** [review]
👌

**Pull request merged**
