### PR TITLE
Add cross-browser testing

### PR DESCRIPTION
**Pull request by fatso83**
Adds cross-browser testing in the cloud and locally using Puppeteer

# Verify
```
export SAUCE_USERNAME=sinonjs
export SAUCE_ACCESS_KEY=3a59ad42-cf59-foo-bar # credentials (available to all maintainers of Sinon)
npm run test-cloud
```

### CODE REVIEW

**Comment by fatso83** [comment]
Running the cloud tests shows IE 11 failing 7 tests:
```
  1) deepEqual
       returns false unequal errors:
     AssertionError: [assert.isFalse] Expected true to be false
      at referee.fail (node_modules/@sinonjs/referee/lib/referee.js:194)
      at ctx.fail (node_modules/@sinonjs/referee/lib/referee.js:84)
      at assertion (node_modules/@sinonjs/referee/lib/referee.js:92)
      at referee[type][name] (node_modules/@sinonjs/referee/lib/referee.js:112)
      at Anonymous function (lib/deep-equal.test.js:318)

  2) deepEqual
       return false if empty object to empty instance:
     AssertionError: [assert.isFalse] Expected true to be false
      at referee.fail (node_modules/@sinonjs/referee/lib/referee.js:194)
      at ctx.fail (node_modules/@sinonjs/referee/lib/referee.js:84)
      at assertion (node_modules/@sinonjs/referee/lib/referee.js:92)
      at referee[type][name] (node_modules/@sinonjs/referee/lib/referee.js:112)
      at Anonymous function (lib/deep-equal.test.js:423)

  3) deepEqual
       returns false if set with the different content:
     AssertionError: [assert.isFalse] Expected true to be false
      at referee.fail (node_modules/@sinonjs/referee/lib/referee.js:194)
      at ctx.fail (node_modules/@sinonjs/referee/lib/referee.js:84)
      at assertion (node_modules/@sinonjs/referee/lib/referee.js:92)
      at referee[type][name] (node_modules/@sinonjs/referee/lib/referee.js:112)
      at Anonymous function (lib/deep-equal.test.js:458)

  4) getClassName
       returns the class name of an instance:
     AssertionError: [assert.equals] undefined expected to be equal to TestClass
      at referee.fail (node_modules/@sinonjs/referee/lib/referee.js:194)
      at ctx.fail (node_modules/@sinonjs/referee/lib/referee.js:84)
      at assertion (node_modules/@sinonjs/referee/lib/referee.js:92)
      at referee[type][name] (node_modules/@sinonjs/referee/lib/referee.js:112)
      at Anonymous function (lib/get-class-name.test.js:14)

  5) getClassName
       returns 'Object' for {}:
     AssertionError: [assert.equals] undefined expected to be equal to Object
      at referee.fail (node_modules/@sinonjs/referee/lib/referee.js:194)
      at ctx.fail (node_modules/@sinonjs/referee/lib/referee.js:84)
      at assertion (node_modules/@sinonjs/referee/lib/referee.js:92)
      at referee[type][name] (node_modules/@sinonjs/referee/lib/referee.js:112)
      at Anonymous function (lib/get-class-name.test.js:19)

  6) match
       returns false if sets with dissimilar content:
     AssertionError: [assert.isFalse] Expected true to be false
      at referee.fail (node_modules/@sinonjs/referee/lib/referee.js:194)
      at ctx.fail (node_modules/@sinonjs/referee/lib/referee.js:84)
      at assertion (node_modules/@sinonjs/referee/lib/referee.js:92)
      at referee[type][name] (node_modules/@sinonjs/referee/lib/referee.js:112)
      at Anonymous function (lib/match.test.js:401)

  7) match
       returns false if sets with different complex member:
     AssertionError: [assert.isFalse] Expected true to be false
      at referee.fail (node_modules/@sinonjs/referee/lib/referee.js:194)
      at ctx.fail (node_modules/@sinonjs/referee/lib/referee.js:84)
      at assertion (node_modules/@sinonjs/referee/lib/referee.js:92)
      at referee[type][name] (node_modules/@sinonjs/referee/lib/referee.js:112)
      at Anonymous function (lib/match.test.js:410)
```

**Comment by fatso83** [comment]
Four of the failing IE11 tests already fail before merging #38 
```
  158 passing (97ms)
  4 failing

  1) deepEqual
       returns false unequal errors:
     AssertionError: [assert.isFalse] Expected true to be false
      at referee.fail (node_modules/@sinonjs/referee/lib/referee.js:194)
      at ctx.fail (node_modules/@sinonjs/referee/lib/referee.js:84)
      at assertion (node_modules/@sinonjs/referee/lib/referee.js:92)
      at referee[type][name] (node_modules/@sinonjs/referee/lib/referee.js:112)
      at Anonymous function (lib/deep-equal.test.js:318)

  2) deepEqual
       returns false if set with the different content:
     AssertionError: [assert.isFalse] Expected true to be false
      at referee.fail (node_modules/@sinonjs/referee/lib/referee.js:194)
      at ctx.fail (node_modules/@sinonjs/referee/lib/referee.js:84)
      at assertion (node_modules/@sinonjs/referee/lib/referee.js:92)
      at referee[type][name] (node_modules/@sinonjs/referee/lib/referee.js:112)
      at Anonymous function (lib/deep-equal.test.js:449)

  3) match
       returns false if sets with dissimilar content:
     AssertionError: [assert.isFalse] Expected true to be false
      at referee.fail (node_modules/@sinonjs/referee/lib/referee.js:194)
      at ctx.fail (node_modules/@sinonjs/referee/lib/referee.js:84)
      at assertion (node_modules/@sinonjs/referee/lib/referee.js:92)
      at referee[type][name] (node_modules/@sinonjs/referee/lib/referee.js:112)
      at Anonymous function (lib/match.test.js:401)

  4) match
       returns false if sets with different complex member:
     AssertionError: [assert.isFalse] Expected true to be false
      at referee.fail (node_modules/@sinonjs/referee/lib/referee.js:194)
      at ctx.fail (node_modules/@sinonjs/referee/lib/referee.js:84)
      at assertion (node_modules/@sinonjs/referee/lib/referee.js:92)
      at referee[type][name] (node_modules/@sinonjs/referee/lib/referee.js:112)
      at Anonymous function (lib/match.test.js:410)
```

Commit 31b4e43 introduced the additional three failing tests:
- deepEqual:       return false if empty object to empty instance
- getClassName:       returns the class name of an instance
-  getClassName:       returns 'Object' for {}:

Ref
- https://github.com/sinonjs/sinon/issues/1882#issuecomment-423939042
- https://github.com/sinonjs/samsam/issues/37
- https://github.com/sinonjs/samsam/pull/38

**Comment by fatso83** [comment]
Now running (and failing as planned): https://travis-ci.org/sinonjs/samsam/jobs/432485630

**Comment by mroderick** [comment]
Admittedly, I don't understand the Sauce Labs setup very well.

When using the same username in all our projects, do the results from all the projects end up getting merged?

Like is the banner below counted for `sinon` or the last project that was built?

[Build Status](https://saucelabs.com/beta/builds/1823060d284742d9aa638cf2d2e423bc)

2018-09-24 at 23 11

If they were collected separately, we should be able to find them separately on https://saucelabs.com/u/sinonjs, right?

**Comment by fatso83** [comment]
Would imagine so. You can tell the different tests apart by looking at the Automated Tests tab, but I am not sure at all if the sauce labs build badge differentiates between different test runs from different projects. We could ask the SL support for input, of course.

**Pull request merged**
