### PR TITLE
Fix all broken tests in IE11

### PR DESCRIPTION
**Pull request by mroderick**
This PR fixes all the failing tests in IE11.

#### Background

See #42 

#### How to verify - mandatory

You'll need to have Sauce Labs configured for `sinonjs` on your computer to be able to verify this PR.

1. Check out this branch
2. `npm install`
3. `npm run test-cloud`

#### Checklist for author

- [x] `npm run lint` passes
- [x] References to standard library functions are [cached](https://github.com/sinonjs/sinon/pull/1523).

### CODE REVIEW

**Comment by mroderick** [comment]
@mgred based on your research and suggestions in #42, I've created this to try to fix the error ... I think that to fix it in sinon, we might have to use a `createError` there also, so that all errors have a populated `stack` property.

We could even go so far as to throw an Error when a passed Error doesn't have a `stack` property, as people that test in IE will run into the same situation as we have.

**Comment by mroderick** [comment]
@fatso83 I believe this is complete now, all tests pass in IE11 for both `samsam` and `sinon`

**Comment by mroderick** [comment]
Thanks

**Comment by mroderick** [comment]
This has been published to npm as `@sinonjs/samsam@2.1.2`

**Comment by fatso83** [comment]
Great stuff, Morgan!

**Comment by mgred** [comment]
:tada: Awesome

**Pull request merged**
