### PR TITLE
Distribute package as source

### PR DESCRIPTION
**Pull request by mroderick**
@khamiltonuk and I spent some time trying to replace `rollup` with `esbuild` only to [discover that it drops comments](https://github.com/evanw/esbuild/issues/578). That would bundling with `esbuild` and providing `.d.ts` files mutually exclusive.

I realised that we don't actually need bundling at all in this project.

---

This library is not meant for writing end user applications or even for being used directly when writing tests. It is not meant to be loaded directly by browsers.

Consumers of this package are assumed to use their own bundlers, should they need to bundle code for use in browsers or workers.

Therefore, it is safe to distribute the package as source files and not bundle them up.

This allows us to remove the bundler and its transitive dependencies, which reduces the maintenance burden of managing the library.

#### Background

* We'd like to ship the library with `.d.ts` files, to allow improved experience for TypeScript users
* We would like to reduce maintenance burden of the library

#### Solution

* Distribute the package as source files
* Create `.d.ts` files from the source files
* Remove the bundler

#### How to verify

1. Check out this branch
1. `npm ci`
1. `npm run build`
1. Observe that there are `.d.ts` files in the `types/` folder
2. `npm pack`
3. Observe that the `.d.ts` files are included in the package
4. `npm link`
5. In a `sinon` checkout:
  1.  `npm link @sinonjs/samsam`
  2. `npm test`
  3. Observe that tests still pass

### CODE REVIEW

**Comment by mroderick** [comment]
We can take this approach to the whole family of Sinon libraries and for `sinon` and `referee` provide bundled versions as well.

Adopting this approach would make it easier to adopt JSDoc to create API docs and `.d.ts` files for packages.

**Comment by mroderick** [comment]
@mshaaban0 would you mind taking this for a spin in a TypeScript project to see if the type hints are still working?

**Review by mantoni — COMMENTED** [review]
This setup means that we have to run `npm run build` to have the source files in the right place when linking locally. I'm wondering if it wouldn't be better to keep everything in `lib` and ship the generated type definitions in a `typings` folder instead of merging everything in `dist`. This isn't a TypeScript project after all, we just want to ship types along with the library. WDYT?

**Comment by mroderick** [comment]
> This setup means that we have to run `npm run build` to have the source files in the right place when linking locally

Do you mean when using it with `npm link`?

**Comment by mantoni** [comment]
> Do you mean when using it with `npm link`?

Yes. And generally, I'm not sure the copy step is needed. Type definitions don't have to sit next to the implementation, AFAIK.

**Comment by mroderick** [comment]
> I'm not sure the copy step is needed. Type definitions don't have to sit next to the implementation, AFAIK.

If they don't, then we could distribute a `types/` folder. That would make things easier.

@mshaaban0 what do you think? Do the types have to sit next to the source files?

**Comment by mroderick** [comment]
```
--outFile FILE                Concatenate and emit output to single file.
--outDir DIRECTORY            Redirect output structure to the directory.
```

These options suggest that we could easily put the output somewhere else. I'll try updating the PR and @mshaaban0 can help verify that it's still working well.

**Review by mshaaban0 — APPROVED** [review]
Screenshot 2021-01-10 at 21 49 50

Works as expected 👍

**Comment by mroderick** [comment]
@hexeberlin and I have pushed new commits for this, using the `outDir` option, pointing it to a `types/` folder. This means that we won't need to run `build` all time time when linking this package, but only for when `npm pack` is run.

@mshaaban0 would you mind doing the test again? ❤️

**Review by mantoni — APPROVED** [review]
Nice!

**Review by mshaaban0 — APPROVED** [review]
Works, thank you 👍

**Comment by mroderick** [comment]
This has been published to the npm registry as `@sinonjs/samsam@5.3.1`

**Pull request merged**
