### PR TITLE
Verify assertions

### PR DESCRIPTION
**Pull request by mantoni**
#### Purpose (TL;DR) - mandatory

With this PR, each test case is required to have at least one referee assertion.

#### Solution  - optional

I was experimenting with the new [`referee.verifier()`](https://sinonjs.github.io/referee/#refereeverifier) utility and Mocha for a while now and found the `--file` option with a global helper to be quite elegant. We don't need to change any of the test cases.

If we're happy with this, we can apply the same to the Sinon project. We could also make the `verifier.js` fixure a new package maybe.

#### How to verify - mandatory
1. Check out this branch
2. `npm install`
3. `npm t` and see that all tests are green
4. Comment out a random assertion
5. `npm t` and see that all tests are green except the one without assertions

#### Checklist for author

- [x] `npm run lint` passes
- [x] References to standard library functions are [cached](https://github.com/sinonjs/sinon/pull/1523).

### CODE REVIEW

**Comment by mantoni** [comment]
Tests are failing in IE 11 due to the lack of Promise support. Sending a patch for Referee to feature detect it and will update this PR once it landed.

**Comment by mantoni** [comment]
Build is fixed. The major updates in the dev tools where necessary to address security issues.

**Comment by mantoni** [comment]
📣 I made this a thing: https://github.com/mantoni/mocha-referee-sinon

**Comment by mgred** [comment]
Nice 👍

**Comment by fatso83** [comment]
Nice! Maybe make this the first user of the new package? If so, fixup commit?

**Comment by mantoni** [comment]
Well, samsam only depends on referee, not referee-sinon, which is what mocha-referee-sinon uses.

**Comment by mroderick** [comment]
Once upon a time, BusterJS had a similar feature (it used the assertion counting feature of `referee`). I can't find it in the documentation just now. For a long time, I thought this was really useful, and I missed the assertion counting feature when I started using Mocha.

Mocha doesn't require anything other than no error thrown to pass a test. This makes for superior flexibility.

I am using [JSVerify](http://jsverify.github.io) more and more, and find it really useful for finding weird edge cases. This tool works really well with Mocha out of the box. Tests look something like this:

```js
describe("some property of a system", function(){
    it("should be magical", function(){
        jsc.assertForall("nestring", function(value) {
            return value.length > 0;
        });
    });
});
```

The return value from the evaluation function passed to `jsc.assertForall` determines if it throws an error, triggering the test runner to fail the test. Any value other than `true` will trigger the error thrown.

I typically use both `referee` and `jsverify` in the same projects, writing simple tests with `referee` first, and then making them better by writing tests with `jsverify` once the domain model is clearer to me.

Requiring a `referee` assertion in a test for it to not fail would be inconvenient, when using non-referee for tests.

```js
describe("some property of a system", function(){
    it("should be magical", function(){
        jsc.assertForall("nestring", function(value) {
            const returnValue = value.length > 0;
            // token assert to please referee.verifier()
            assert.isTrue(returnValue);
            
            return returnValue;
        });
    });
});
```

I would very much like our tools to play nice with each other. If this is something we want to move forwards with, I think it would be wise to document it really well, so people will know what the tradeoffs are when they decide to use it.

**Comment by mantoni** [comment]
If we want to introduce new tools like JSVerify, then the verification count assertions are potentially annoying. I can see that. I wasn't aware that you're interested in changing the test setup. I don't have strong opinions or feelings about it. I wrote the helper for my own use and shared it here.

I guess the question is, do we want to keep the flexibility of having alternatives to referee in tests? Or are we fine with working around it?

Another ramdom thought: The helper has access to test meta information, which would make it possible to somehow annotate the test to skip assertion verification. Maybe too hacky, not sure.

**Comment by mroderick** [comment]
We are using `jsverify` in commons: https://github.com/sinonjs/commons/blob/cec1205e776c2a279bd6d540e290257b970a18e0/lib/function-name.test.js

Like I said above, I do like the assertion counting feature and that it fails tests without assertions. I wonder if we can count `jsc.assertForall` as an assertion?

**Comment by mantoni** [comment]
it would be nice if `jsverify` would emit events or provide some other hook, but I didn't find anything like that in the docs. We could alternatively wrap `jsc.assertForall` with a spy and check the call count 😆

**Comment by mroderick** [comment]
> We could alternatively wrap `jsc.assertForall` with a spy and check the call count 😆

I think that might our test setup from trivial to non-trivial. Let's think on it some more

**Comment by mantoni** [comment]
Closing as it has conflicts. I'm simply using https://github.com/mantoni/mocha-referee-sinon in my projects now.

**Pull request closed without merging**
